package cn.com.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}

	public java.lang.Integer getMid() {
		return get("mid");
	}

	public void setTxtName(java.lang.String txtName) {
		set("txt_name", txtName);
	}

	public java.lang.String getTxtName() {
		return get("txt_name");
	}

	public void setPId(java.lang.Integer pId) {
		set("p_id", pId);
	}

	public java.lang.Integer getPId() {
		return get("p_id");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setSeqNo(java.lang.Integer seqNo) {
		set("seq_no", seqNo);
	}

	public java.lang.Integer getSeqNo() {
		return get("seq_no");
	}

	public void setIconClass(java.lang.String iconClass) {
		set("icon_class", iconClass);
	}

	public java.lang.String getIconClass() {
		return get("icon_class");
	}

}
