package cn.com.admin.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_menu", "mid", SysMenu.class);
		arp.addMapping("sys_role", "rid", SysRole.class);
		arp.addMapping("sys_role_menu_rela", "id", SysRoleMenuRela.class);
		arp.addMapping("sys_user", "uid", SysUser.class);
	}
}

