package cn.com.admin.common.model;

import cn.com.admin.common.model.base.BaseSysRoleMenuRela;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMenuRela extends BaseSysRoleMenuRela<SysRoleMenuRela> {
	public static final SysRoleMenuRela dao = new SysRoleMenuRela();

	/**
	 * 查询
	 * @param rid
	 * @return
     */
	public List queryMenuIds(Integer rid) {
		return find("SELECT * FROM sys_role_menu_rela WHERE rid = ? ",rid);
	}

	/**
	 * 用rid删除
	 * @param rid
     */
	public void deleteByRid(Integer rid) {
		Db.update("DELETE FROM sys_role_menu_rela WHERE rid = ?", rid);
	}

	/**
	 * 指插入rid,
	 * @param mid
	 * @param rid
     */
	public void insertValues(String[] mid, Integer rid) {
		Object[][] o = new Object[mid.length][2] ;
		for (int i = 0; i < mid.length; i++) {
			o[i][1] = mid[i] ;
			o[i][0] = rid ;
		}
		Db.batch("INSERT INTO sys_role_menu_rela SET rid = ?,mid = ?", o ,mid.length);
	}
}
