package cn.com.admin.common.model;

import cn.com.admin.common.result.DatagridPage;
import cn.com.admin.common.model.base.BaseSysUser;
import cn.com.admin.common.util.Conditions;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	private String startTime ;
	private String endTime ;

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public static final SysUser dao = new SysUser();

	/**
	 * 查询列表数据
	 * @param user
	 * @param pageNumber
	 * @param pageSize
     * @return
     */
	public DatagridPage queryForList(SysUser user,Integer pageNumber,Integer pageSize) {
		Conditions c = new Conditions() ;

		c.setFiledQuery(Conditions.EQUAL,"is_used");
		c.setFiledQuery(Conditions.FUZZY,"uname");
		c.setValueQuery(Conditions.GREATER_EQUAL,"create_time",user.getStartTime());
		c.setValueQuery(Conditions.LESS_EQUAL,"create_time",user.getEndTime());

		c.modelToCondition(user);
		return DatagridPage.toGridPage(user.paginate(pageNumber, pageSize, "SELECT *", "FROM sys_user WHERE 1=1 " + c.getSql() + " ORDER BY uid DESC ",c.getParamList().toArray(new String[]{}))) ;
	}

	public SysUser findUserFirst(String uname, String pwd) {
		return findFirst("SELECT * FROM sys_user WHERE uname = ? AND pwd = ? AND is_used = 1 ",new Object[]{uname,pwd}) ;
	}
}
